### ISSUE TITLE
ClassNotFoundException: taoensso.encore

### ISSUE THREAD

**Issue by jaydeesimon** [taoensso/truss#1]
I'm trying out Truss (1.1.0) and am having a compilation issue. Details are in the screenshot but let me know if you need more information. I must be doing something wrong.
![screen shot 2016-02-18 at 9 45 57 am](https://cloud.githubusercontent.com/assets/6627904/13146669/da78fdc2-d624-11e5-9072-0651b8705d0c.png)

Thanks in advance.

**Comment by ptaoussanis** [comment]
Hey there, thanks for the report - this was a mistake on my end. Normally have encore loaded myself so didn't catch this.

Should be fixed on `[com.taoensso/truss "1.1.1"]` (just pushed to Clojars).

**Comment by jaydeesimon** [comment]
Thanks for the quick reply. I just pulled down the new jar and is working great.

By the way, I came across your library because Youtube suggested I watch your video. Just wanted to let you know I thought the demo of your library was well-done and I'm glad to see someone who's working to improve the experience with Clojure error messages. Thanks again.

**Comment by ptaoussanis** [comment]
You're very welcome, thanks for saying so. Cheers :-)
