### ISSUE TITLE
document the awesome `:in` modifier

### ISSUE THREAD

**Issue by avocade** [taoensso/truss#15]
Using `:in` for asserting inside a collection is great, but it's not described in many places. 

Should be at least in the docs: https://cljdoc.org/d/com.taoensso/truss/1.11.0/api/taoensso.truss#have

But probably also in the main README.

I'll make a PR for this next week if my brain's still with me after this weekend :)

Thanks for a tiny great lib 🙏

**Comment by ptaoussanis** [comment]
@avocade Hi Oskar, thanks for this!

I've taken the opportunity (and your enthusiasm) to clean up a bit and improve the docstrings in general.

Will cut a new release shortly.

Also, in case you missed it - there's also more info in the [wiki](https://github.com/taoensso/truss/wiki/1-Getting-started).

Cheers!
