### ISSUE TITLE
Assertion in set and list returns a vector

### ISSUE THREAD

**Issue by Rovanion** [taoensso/truss#9]
It seems like assertions that something `:in X` always return a vector:

```clojure
(truss/have integer? :in [1 2 3])     ; => [1 2 3]
(truss/have integer? :in '(1 2 3))    ; => [1 2 3]
(truss/have integer? :in #{1 2 3})    ; => [1 3 2]
```

I'd expect to have returned the same data as I passed in case the assert was successful.

**Comment by ptaoussanis** [comment]
Hi Rovanion, good idea- will make this change shortly. Thanks! 👍
